**Series - 1D array**

In [4]:
import pandas as pd

marks = pd.Series([10,45,34,62,29,43.5,"pakistan"])
print(marks)
print(marks[6])

0          10
1          45
2          34
3          62
4          29
5        43.5
6    pakistan
dtype: object
pakistan

In [5]:
print(marks.index)

RangeIndex(start=0, stop=7, step=1)

In [6]:
result = pd.Series([10,45,34,62,29,43], index=["Ali","Sara","Farooq","Ahmad","Javed","Imran"])
print(result)
print(result['Farooq'])

Ali       10
Sara      45
Farooq    34
Ahmad     62
Javed     29
Imran     43
dtype: int64
34

In [7]:
print(result.index)
print(result.values)

Index(['Ali', 'Sara', 'Farooq', 'Ahmad', 'Javed', 'Imran'], dtype='str')
[10 45 34 62 29 43]

**Series using Dictionaries**

In [8]:
st_marks = pd.Series({"Ali":10,"Sara":45,"Farooq":34,"Ahmad":62,"Javed":29,"Imran":43})
print(st_marks)
print(st_marks['Ahmad'])
print(st_marks.iloc[3])

Ali       10
Sara      45
Farooq    34
Ahmad     62
Javed     29
Imran     43
dtype: int64
62
62

In [9]:
print(st_marks.iloc[1:3])

Sara      45
Farooq    34
dtype: int64

In [10]:
print(st_marks[['Farooq','Javed']]+5)

Farooq    39
Javed     34
dtype: int64

0h:23m <br>
**DataFrame  - Rows and Columns** <br>
- A **DataFrame** is a full table

In [11]:
students = pd.DataFrame({
            "name":["Ali","Ahmad","Usman","Javed","Farooq"],
            "age":[17,19,24,21,18],
            "city":["karachi","lahore","multan","islamabad","quetta"],
            "marks":[45,54,56,43,67]
    })

print(students)

#to retrieve a column
print(students['city'])

#to retrieve a row
print(students.iloc[0])

     name  age       city  marks
0     Ali   17    karachi     45
1   Ahmad   19     lahore     54
2   Usman   24     multan     56
3   Javed   21  islamabad     43
4  Farooq   18     quetta     67
0      karachi
1       lahore
2       multan
3    islamabad
4       quetta
Name: city, dtype: str
name         Ali
age           17
city     karachi
marks         45
Name: 0, dtype: object

In [16]:
print(f"Dataframe has {students.shape[0]} rows and {students.shape[1]} columns")
print(students.ndim)
print(students.size)
print(students.dtypes)
print(students.columns)
print(students.index)

Dataframe has 5 rows and 4 columns
2
20
name       str
age      int64
city       str
marks    int64
dtype: object
Index(['name', 'age', 'city', 'marks'], dtype='str')
RangeIndex(start=0, stop=5, step=1)

In [18]:
r,c = students.shape
print(f"{r} rows {c} columns")
print(students.info())

5 rows 4 columns
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      int64
 2   city    5 non-null      str
 3   marks   5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes
None

0h:46m <br>
**Loading real data**
1. **From a .CSV file** <br>
    df = pd.read_csv() <br>
2. **From built-in sample dataset** (needs `seaborn` library) <br>
    df = sns.load_dataset("titanic")

In [24]:
import seaborn as sns
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

In [35]:
ds_titanic = sns.load_dataset("titanic")
print(ds_titanic.shape)
print(ds_titanic.columns)
print(ds_titanic.info())

(891, 15)
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB
None

In [60]:
ds_titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [62]:
print(ds_titanic.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [63]:
#prints first 5 rows
ds_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [64]:
#prints last 5 rows
ds_titanic.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [65]:
#prints first 10 rows
ds_titanic.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [66]:
ds_titanic.tail(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [67]:
#returns random 5 rows
ds_titanic.sample(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
655,0,2,male,24.0,2,0,73.5000,S,Second,man,True,NaN,Southampton,no,False
805,0,3,male,31.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
717,1,2,female,27.0,0,0,10.5000,S,Second,woman,False,E,Southampton,yes,True
806,0,1,male,39.0,0,0,0.0000,S,First,man,True,A,Southampton,no,True
397,0,2,male,46.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
215,1,1,female,31.0,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
245,0,1,male,44.0,2,0,90.0000,Q,First,man,True,C,Queenstown,no,False
826,0,3,male,NaN,0,0,56.4958,S,Third,man,True,NaN,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False

In [68]:
ds_titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [69]:
#missing values's sum
ds_titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

**Selecting Columns** <br>
- df['age'] - one set of square brackets - returns a series
- df[['age','fare']] - two sets - returns a dataframe

In [81]:
ages = ds_titanic['age'].mean()
print(ages)

29.69911764705882