In [2]:
import pandas as pd
import seaborn as sb
import numpy as np

titanic = sb.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

**selecting rows**

In [3]:
titanic.iloc[2]

survived                 1
pclass                   3
sex                 female
age                   26.0
sibsp                    0
parch                    0
fare                 7.925
embarked                 S
class                Third
who                  woman
adult_male           False
deck                   NaN
embark_town    Southampton
alive                  yes
alone                 True
Name: 2, dtype: object

In [4]:
titanic.iloc[0:3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [5]:
#last value inclusive
titanic.loc[0:3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False

In [6]:
#filtering rows and columns
titanic[['survived','pclass','sex','age','alive']]

     survived  pclass     sex   age alive
0           0       3    male  22.0    no
1           1       1  female  38.0   yes
2           1       3  female  26.0   yes
3           1       1  female  35.0   yes
4           0       3    male  35.0    no
..        ...     ...     ...   ...   ...
886         0       2    male  27.0    no
887         1       1  female  19.0   yes
888         0       3  female   NaN    no
889         1       1    male  26.0   yes
890         0       3    male  32.0    no

[891 rows x 5 columns]

In [7]:
titanic.loc[0:4,['sex','age','alive','pclass']]

      sex   age alive  pclass
0    male  22.0    no       3
1  female  38.0   yes       1
2  female  26.0   yes       3
3  female  35.0   yes       1
4    male  35.0    no       3

In [8]:
titanic.iloc[0:3,0:4]

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0

In [9]:
#single cell
print("Age of passenger at index 2:",titanic.iloc[2]['age'])
print("Age of passenger at index 2:",titanic.loc[2,'age'])

Age of passenger at index 2: 26.0
Age of passenger at index 2: 26.0

**Boolean Filtering**

In [10]:
bool_over_30 = titanic['age']>30
print(bool_over_30)
print(bool_over_30.sum())

0      False
1       True
2      False
3       True
4       True
       ...
886    False
887    False
888    False
889    False
890     True
Name: age, Length: 891, dtype: bool
305

In [11]:
titanic[bool_over_30]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [12]:
#return males belonging to class 1
class1 = titanic['pclass'] == 1
males = titanic['sex']=='male'

class1_males = class1 & males
# titanic[class1][males]
# print(titanic[class1_males])

# filter class1, males, age<20
age_below_20 = titanic['age']<20

class1_male_age_below_20 = class1_males & age_below_20
print(titanic[class1_male_age_below_20])
print(class1_male_age_below_20.sum())

     survived  pclass   sex    age  sibsp  parch      fare embarked  class  \
27          0       1  male  19.00      3      2  263.0000        S  First
305         1       1  male   0.92      1      2  151.5500        S  First
445         1       1  male   4.00      0      2   81.8583        S  First
505         0       1  male  18.00      1      0  108.9000        C  First
550         1       1  male  17.00      0      2  110.8833        C  First
748         0       1  male  19.00      1      0   53.1000        S  First
802         1       1  male  11.00      1      2  120.0000        S  First

       who  adult_male deck  embark_town alive  alone
27     man        True    C  Southampton    no  False
305  child       False    C  Southampton   yes  False
445  child       False    A  Southampton   yes  False
505    man        True    C    Cherbourg    no  False
550    man        True    C    Cherbourg   yes  False
748    man        True    D  Southampton    no  False
802  child       False    B  Southampton   yes  False
7

In [13]:
mask = titanic['age']>30
print(titanic[mask].shape[0])
print(mask.sum())

male = titanic['sex']=='male'
print(male.sum())
print(titanic[male].shape[0])
print(titanic[male])

305
305
577
577
     survived  pclass   sex   age  sibsp  parch     fare embarked   class  \
0           0       3  male  22.0      1      0   7.2500        S   Third
4           0       3  male  35.0      0      0   8.0500        S   Third
5           0       3  male   NaN      0      0   8.4583        Q   Third
6           0       1  male  54.0      0      0  51.8625        S   First
7           0       3  male   2.0      3      1  21.0750        S   Third
..        ...     ...   ...   ...    ...    ...      ...      ...     ...
883         0       2  male  28.0      0      0  10.5000        S  Second
884         0       3  male  25.0      0      0   7.0500        S   Third
886         0       2  male  27.0      0      0  13.0000        S  Second
889         1       1  male  26.0      0      0  30.0000        C   First
890         0       3  male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
4      man        True  NaN  Southampton    no   True
5      man        True  NaN   Queenstown    no   True
6      man        True    E  Southampton    no   True
7    child       False  NaN  Southampton    no  False
..     ...         ...  ...          ...   ...    ...
883    man        True  NaN  Southampton    no   True
884    man        True  NaN  Southampton    no   True
886    man        True  NaN  Southampton    no   True
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[577 rows x 15 columns]

In [14]:
#return no. of alive passengers
print(titanic[titanic['alive']=='yes'])
alive=titanic[titanic['alive']=='yes']
# print(titanic['alive'].value_counts())
print(alive.shape[0])

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
8           1       3  female  27.0      0      2  11.1333        S   Third
9           1       2  female  14.0      1      0  30.0708        C  Second
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
875         1       3  female  15.0      0      0   7.2250        C   Third
879         1       1  female  56.0      0      1  83.1583        C   First
880         1       2  female  25.0      0      1  26.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
889         1       1    male  26.0      0      0  30.0000        C   First

       who  adult_male deck  embark_town alive  alone
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
8    woman       False  NaN  Southampton   yes  False
9    child       False  NaN    Cherbourg   yes  False
..     ...         ...  ...          ...   ...    ...
875  child       False  NaN    Cherbourg   yes   True
879  woman       False    C    Cherbourg   yes  False
880  woman       False  NaN  Southampton   yes  False
887  woman       False    B  Southampton   yes   True
889    man        True    C    Cherbourg   yes   True

[342 rows x 15 columns]
342

**Combining Conditions** <br>
- & | ~

In [15]:
# Females and Survived
female_survived = titanic[(titanic['sex']=="female") & (titanic['survived']==1)]
print(female_survived.shape[0])
female_survived.head()

233

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [16]:
#filter columns from the output
ff = female_survived[['survived','pclass','sex','age']]
ff.head()

   survived  pclass     sex   age
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
8         1       3  female  27.0
9         1       2  female  14.0

In [17]:
# first class or second class but female only

f12 = titanic[((titanic['pclass']==1) | (titanic['pclass']==2)) & (titanic['sex']=='female')]
# print(titanic.sample(15))
f12.head(15)
# f12.shape[0]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
41,0,2,female,27.0,1,0,21.0000,S,Second,woman,False,NaN,Southampton,no,False
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
53,1,2,female,29.0,1,0,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
56,1,2,female,21.0,0,0,10.5000,S,Second,woman,False,NaN,Southampton,yes,True
58,1,2,female,5.0,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
61,1,1,female,38.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
66,1,2,female,29.0,0,0,10.5000,S,Second,woman,False,F,Southampton,yes,True
84,1,2,female,17.0,0,0,10.5000,S,Second,woman,False,NaN,Southampton,yes,True

In [18]:
f12 = f12[['survived','pclass','sex','age','alive']]
f12.head(15)

    survived  pclass     sex   age alive
1          1       1  female  38.0   yes
3          1       1  female  35.0   yes
9          1       2  female  14.0   yes
11         1       1  female  58.0   yes
15         1       2  female  55.0   yes
31         1       1  female   NaN   yes
41         0       2  female  27.0    no
43         1       2  female   3.0   yes
52         1       1  female  49.0   yes
53         1       2  female  29.0   yes
56         1       2  female  21.0   yes
58         1       2  female   5.0   yes
61         1       1  female  38.0   yes
66         1       2  female  29.0   yes
84         1       2  female  17.0   yes

In [19]:
#passenger who did not survive
not_sur = titanic[~(titanic['survived']==1)]
not_sur = not_sur[['survived','pclass','sex','age','alive']]

not_sur.head(15)
# not_sur.shape[0]
# titanic['survived'].value_counts()

    survived  pclass     sex   age alive
0          0       3    male  22.0    no
4          0       3    male  35.0    no
5          0       3    male   NaN    no
6          0       1    male  54.0    no
7          0       3    male   2.0    no
12         0       3    male  20.0    no
13         0       3    male  39.0    no
14         0       3  female  14.0    no
16         0       3    male   2.0    no
18         0       3  female  31.0    no
20         0       2    male  35.0    no
24         0       3  female   8.0    no
26         0       3    male   NaN    no
27         0       1    male  19.0    no
29         0       3    male   NaN    no

0h:41m <br>
`.isin()` - a shortcut for many OR's <br>
Writing (x=='a') | (x=='b') | (x=='c') gets ugly fast <br>
isin() does it cleanly.

In [20]:
# the long way
long_way = titanic[(titanic['pclass'] == 1) | (titanic['pclass'] ==2)]

# the clean way
clean_way = titanic[titanic['pclass'].isin([1,2])]
clean_way.head(15)
print(long_way.shape[0])
print(clean_way.shape[0])

400
400

**.between()** - a shortcut for ranges

In [21]:
# the long way
# passenger between 13 and 19 years of age

long_way = titanic[(titanic['age']>=13) & (titanic['age']<=19)]
print(long_way.shape[0])

# clean way
clean_way = titanic[titanic['age'].between(13,19)]
print(clean_way.shape[0])

95
95

In [22]:
women = titanic[titanic['sex']=='female']
men = titanic[titanic['sex']=='male']
print(round(women['survived'].mean(),2))
print(round(men['survived'].mean(),2))

0.74
0.19

In [23]:
# find the average fare of each class
for c in [1,2,3]:
    cl = titanic['pclass']==c
    cl_fare = titanic[cl]['fare'].mean()
    print(f"Class {c} avg. fare: {round(cl_fare,2)}")

for c in [1,2,3]:
    cl= titanic[titanic['pclass']==c]
    cl_fare = cl['fare'].mean()
    print(f"Class {c} avg. fare: {round(cl_fare,2)}")

Class 1 avg. fare: 84.15
Class 2 avg. fare: 20.66
Class 3 avg. fare: 13.68
Class 1 avg. fare: 84.15
Class 2 avg. fare: 20.66
Class 3 avg. fare: 13.68

In [24]:
# find the average age of passengers in each class

for c in [1,2,3]:
    cl = titanic[titanic['pclass']==c]
    print(f"Avg. age of class {c}: {round(cl['age'].mean(),2)}")

Avg. age of class 1: 38.23
Avg. age of class 2: 29.88
Avg. age of class 3: 25.14

0h:51m <br>
**Sorting** <br>
`sort_values()` orders rows by column in ascending order

In [25]:
#oldest passenger first
titanic.sort_values(by="age",ascending=False)[['age','pclass','survived','fare','sex']].head()
titanic.sort_values(by="age")[['age','pclass','survived','fare','sex']].head()

      age  pclass  survived     fare     sex
803  0.42       3         1   8.5167    male
755  0.67       2         1  14.5000    male
644  0.75       3         1  19.2583  female
469  0.75       3         1  19.2583  female
78   0.83       2         1  29.0000    male

In [26]:
# Cheapest fare first 
titanic.sort_values(by="fare").head(50)

# Most expensive fare first
titanic.sort_values(by="fare" ,ascending=False).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False

0h:57m <br>
**Sorting by two columns** <br>
Pass a list. it sorts by the first, then breaks ties with the second.

In [27]:
titanic.sort_values(by=["pclass","fare"], ascending=[True,False])[['survived','pclass','fare','age','sex']].head()
# titanic.sort_values(by=["pclass","age"]).head(15)

     survived  pclass      fare   age     sex
258         1       1  512.3292  35.0  female
679         1       1  512.3292  36.0    male
737         1       1  512.3292  35.0    male
27          0       1  263.0000  19.0    male
88          1       1  263.0000  23.0  female

1h:00m <br>
`.nlargest()` and `.nsmallest()` -  a shortcut <br>
when you only want the top N, this is shorter and faster than sorting the whole table.

In [28]:
# 5 most expensive tickets
titanic.nlargest(5, "fare")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False

In [29]:
titanic.sort_values(by="fare", ascending=False).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False

In [30]:
#5 youngest passengers
titanic.nsmallest(5,"age")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False

1h:03m <br>
**Adding, Renaming and Dropping columns** <br>
Adding a column <br>
just assign a new name. The calculation happens for every row at once

In [31]:
# work on a copy so we don't damage the original.
titanic_copy = titanic.copy()
titanic_copy
titanic_copy.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [32]:
titanic_copy['family_size'] = titanic_copy['sibsp'] + titanic_copy['parch'] + 1
titanic_copy.columns
titanic_copy.head(10)
titanic_copy.nlargest(10,"family_size")[['survived','pclass','sex','age','sibsp','parch','family_size']]

     survived  pclass     sex   age  sibsp  parch  family_size
159         0       3    male   NaN      8      2           11
180         0       3  female   NaN      8      2           11
201         0       3    male   NaN      8      2           11
324         0       3    male   NaN      8      2           11
792         0       3  female   NaN      8      2           11
846         0       3    male   NaN      8      2           11
863         0       3  female   NaN      8      2           11
59          0       3    male  11.0      5      2            8
71          0       3  female  16.0      5      2            8
386         0       3    male   1.0      5      2            8

In [33]:
print(titanic_copy.columns)
print(titanic.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'family_size'],
      dtype='str')
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

why `.copy()`? <br>
if you write df = titanic you do not get a new table. you get a second name pointing at the same table. Chnage one and the other changes too.
<br>
.copy() makes a real, seperate copy. use it whenever you plan to modify a DataFrame.

1h:11m <br>
**Renaming Columns** <br>

In [39]:
titanic_copy.columns 
titanic_copy = titanic_copy.rename(columns={"sex":"gender","sibsp":"siblings_spouse","parch":"parents_children"})
titanic_copy.columns
titanic_copy

,survived,pclass,gender,age,siblings_spouse,parents_children,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,1
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,4
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1