In [25]:
import pandas as pd
import seaborn as sb
import numpy as np

titanic = sb.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

**selecting rows**

In [26]:
titanic.iloc[2]

survived                 1
pclass                   3
sex                 female
age                   26.0
sibsp                    0
parch                    0
fare                 7.925
embarked                 S
class                Third
who                  woman
adult_male           False
deck                   NaN
embark_town    Southampton
alive                  yes
alone                 True
Name: 2, dtype: object

In [27]:
titanic.iloc[0:3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [28]:
#last value inclusive
titanic.loc[0:3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False

In [29]:
#filtering rows and columns
titanic[['survived','pclass','sex','age','alive']]

     survived  pclass     sex   age alive
0           0       3    male  22.0    no
1           1       1  female  38.0   yes
2           1       3  female  26.0   yes
3           1       1  female  35.0   yes
4           0       3    male  35.0    no
..        ...     ...     ...   ...   ...
886         0       2    male  27.0    no
887         1       1  female  19.0   yes
888         0       3  female   NaN    no
889         1       1    male  26.0   yes
890         0       3    male  32.0    no

[891 rows x 5 columns]

In [30]:
titanic.loc[0:4,['sex','age','alive','pclass']]

      sex   age alive  pclass
0    male  22.0    no       3
1  female  38.0   yes       1
2  female  26.0   yes       3
3  female  35.0   yes       1
4    male  35.0    no       3

In [31]:
titanic.iloc[0:3,0:4]

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0

In [32]:
#single cell
print("Age of passenger at index 2:",titanic.iloc[2]['age'])
print("Age of passenger at index 2:",titanic.loc[2,'age'])

Age of passenger at index 2: 26.0
Age of passenger at index 2: 26.0

**Boolean Filtering**

In [33]:
bool_over_30 = titanic['age']>30
print(bool_over_30)
print(bool_over_30.sum())

0      False
1       True
2      False
3       True
4       True
       ...
886    False
887    False
888    False
889    False
890     True
Name: age, Length: 891, dtype: bool
305

In [34]:
titanic[bool_over_30]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [50]:
#return males belonging to class 1
class1 = titanic['pclass'] == 1
males = titanic['sex']=='male'

class1_males = class1 & males
# titanic[class1][males]
# print(titanic[class1_males])

# filter class1, males, age<20
age_below_20 = titanic['age']<20

class1_male_age_below_20 = class1_males & age_below_20
print(titanic[class1_male_age_below_20])
print(class1_male_age_below_20.sum())

     survived  pclass   sex    age  sibsp  parch      fare embarked  class  \
27          0       1  male  19.00      3      2  263.0000        S  First
305         1       1  male   0.92      1      2  151.5500        S  First
445         1       1  male   4.00      0      2   81.8583        S  First
505         0       1  male  18.00      1      0  108.9000        C  First
550         1       1  male  17.00      0      2  110.8833        C  First
748         0       1  male  19.00      1      0   53.1000        S  First
802         1       1  male  11.00      1      2  120.0000        S  First

       who  adult_male deck  embark_town alive  alone
27     man        True    C  Southampton    no  False
305  child       False    C  Southampton   yes  False
445  child       False    A  Southampton   yes  False
505    man        True    C    Cherbourg    no  False
550    man        True    C    Cherbourg   yes  False
748    man        True    D  Southampton    no  False
802  child       False    B  Southampton   yes  False
7

In [48]:
mask = titanic['age']>30
print(titanic[mask].shape[0])
print(mask.sum())

male = titanic['sex']=='male'
print(male.sum())
print(titanic[male].shape[0])
print(titanic[male])

305
305
577
577
     survived  pclass   sex   age  sibsp  parch     fare embarked   class  \
0           0       3  male  22.0      1      0   7.2500        S   Third
4           0       3  male  35.0      0      0   8.0500        S   Third
5           0       3  male   NaN      0      0   8.4583        Q   Third
6           0       1  male  54.0      0      0  51.8625        S   First
7           0       3  male   2.0      3      1  21.0750        S   Third
..        ...     ...   ...   ...    ...    ...      ...      ...     ...
883         0       2  male  28.0      0      0  10.5000        S  Second
884         0       3  male  25.0      0      0   7.0500        S   Third
886         0       2  male  27.0      0      0  13.0000        S  Second
889         1       1  male  26.0      0      0  30.0000        C   First
890         0       3  male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
4      man        True  NaN  Southampton    no   True
5      man        True  NaN   Queenstown    no   True
6      man        True    E  Southampton    no   True
7    child       False  NaN  Southampton    no  False
..     ...         ...  ...          ...   ...    ...
883    man        True  NaN  Southampton    no   True
884    man        True  NaN  Southampton    no   True
886    man        True  NaN  Southampton    no   True
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[577 rows x 15 columns]