In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [4]:
isn_mean = round(titanic.isnull().mean()*100,1)
isn = titanic.isnull().sum()
repor = pd.DataFrame({
   "missing_count": isn[isn>0],
   "missing_percentage": isn_mean[isn_mean>0]
})
repor

             missing_count  missing_percentage
age                    177                19.9
embarked                 2                 0.2
deck                   688                77.2
embark_town              2                 0.2

In [5]:
missing_sum = titanic.isnull().sum()

report = pd.DataFrame({
    "missing_count": titanic.isnull().sum(),
    "missing (%)":round(titanic.isnull().mean()*100,1)
})

report[report['missing_count']>0]

             missing_count  missing (%)
age                    177         19.9
embarked                 2          0.2
deck                   688         77.2
embark_town              2          0.2

In [6]:
clean_titanic = titanic.copy()
clean_titanic.info()
print(clean_titanic.shape)
print(len(clean_titanic))

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB
(891, 15)
891

In [7]:
print(f"Before: {len(clean_titanic)}")
post_dropna = clean_titanic.dropna()
print(f"After: {len(post_dropna)}")
print(f"Lost: {len(clean_titanic) - len(post_dropna)}")
print(len(post_dropna)/len(clean_titanic)*100)
post_dropna.sample(15)

Before: 891
After: 182
Lost: 709
20.42648709315376

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
627,1,1,female,21.0,0,0,77.9583,S,First,woman,False,D,Southampton,yes,True
318,1,1,female,31.0,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
310,1,1,female,24.0,0,0,83.1583,C,First,woman,False,C,Cherbourg,yes,True
174,0,1,male,56.0,0,0,30.6958,C,First,man,True,A,Cherbourg,no,True
248,1,1,male,37.0,1,1,52.5542,S,First,man,True,D,Southampton,yes,False
66,1,2,female,29.0,0,0,10.5000,S,Second,woman,False,F,Southampton,yes,True
194,1,1,female,44.0,0,0,27.7208,C,First,woman,False,B,Cherbourg,yes,True
369,1,1,female,24.0,0,0,69.3000,C,First,woman,False,B,Cherbourg,yes,True
741,0,1,male,36.0,1,0,78.8500,S,First,man,True,C,Southampton,no,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
452,0,1,male,30.0,0,0,27.7500,C,First,man,True,C,Cherbourg,no,True
853,1,1,female,16.0,0,1,39.4000,S,First,woman,False,D,Southampton,yes,False
215,1,1,female,31.0,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False

**`subset=`  only care about specific columns**

In [8]:
post_dropna = clean_titanic.dropna(subset=['embarked','embark_town'])
len(post_dropna)

889

**`how='any'` vs `how='all'`**

In [9]:
drop_any = clean_titanic.dropna(how='any')
drop_any
drop_how_all = clean_titanic.dropna(how='all')
drop_how_all

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

**`axis=1`  -   drop columns instead of rows**

In [10]:
drop_col = clean_titanic.dropna(axis=1)
print(len(clean_titanic.columns))
len(drop_col.columns)

15

11

5. **List comprehension**

In [11]:
[c for c in clean_titanic.columns if c not in drop_col]

['age', 'embarked', 'deck', 'embark_town']

5.1 **Regular way / Alternate method for List comprehension**

In [17]:
dc = []
for c in clean_titanic.columns:
    if c not in drop_col.columns:
        dc.append(c)

print(f"Columns removed: {dc}")

Columns removed: ['age', 'embarked', 'deck', 'embark_town']

In [27]:
#deck is 77% empty so we drop it on purpose.
titanic1 =  titanic.copy()
clean_titanic = titanic1.drop(columns=['deck'])
# clean_titanic = titanic1.dropna(subset=['deck'], axis=1)
clean_titanic
# clean_titanic.shape

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

6. **Filling missing values with `.fillna()`** <br>

 -  6.1 Filling with a constant

In [30]:
len(titanic1.columns)
titanic1.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')